Repository BrightCoders-Institute/BCDIC22-RN-proyecto-final-team3, pull requests merged in 2023-03, with the labels that each got.

#14 Feat/#11 Log in text input
  package-lock.json
  package.json
  src/components/CTextInput.tsx
  src/navigation/InFollowing.tsx
  src/navigation/InForms.tsx
  src/navigation/InGps.tsx
  src/navigation/Index.tsx
  src/navigation/LoggedTab.tsx
  src/navigation/NotLoggedTab.tsx
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
  src/screens/LogIn.tsx
  src/screens/Settings.tsx
  src/screens/SignUp.tsx
  src/styles/components/CTextInput.ts
  src/styles/screens/Details.ts
  src/styles/screens/Following.ts
  src/styles/screens/Gps.ts
  src/styles/screens/LogIn.ts
  src/styles/screens/Settings.ts
  src/styles/screens/SignUp.ts
  src/types/Details.ts
  src/types/LogIn.ts
  src/types/Settings.ts
  src/types/SignUp.ts
  src/types/components/CTextInput.ts
  src/types/navigation/InFollowing.ts
  src/types/navigation/InForms.ts
  src/types/navigation/InGps.ts
  src/types/navigation/LoggedTab.ts
  src/types/navigation/NotLoggedTab.ts
  src/types/navigation/RootStackParamList.ts
  src/types/screens/Details.ts
  src/types/screens/Following.ts
  src/types/screens/Gps.ts
  src/types/screens/LogIn.ts
  src/types/screens/Settings.ts
  src/types/screens/SignUp.ts
  src/types/theme/ThemeContext.ts
Labels: @IvanGodinez21

#15 Feat/#12 Log in button
  App.tsx
  src/components/CButton.tsx
  src/components/CTextInput.tsx
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
  src/screens/LogIn.tsx
  src/screens/Settings.tsx
  src/screens/SignUp.tsx
  src/styles/components/CButton.ts
  src/styles/components/CTextInput.ts
  src/styles/screens/Details.ts
  src/styles/screens/Following.ts
  src/styles/screens/Gps.ts
  src/styles/screens/LogIn.ts
  src/styles/screens/Settings.ts
  src/styles/screens/SignUp.ts
  src/theme/ThemeContext.ts
  src/theme/colors.ts
  src/theme/context.ts
  src/theme/theme.ts
  src/theme/themes.ts
  src/types/components/CButton.ts
  src/types/components/CTextInput.ts
  src/types/theme/context.ts
Labels: @IvanGodinez21

#16 Feat/#13 Log in with Google button
  App.tsx
  docs/planning.md
  src/assets/adaptive-icon.png
  src/assets/icon.png
  src/assets/splash.png
  src/assets/wwu.png
  src/components/CButton.tsx
  src/components/CButtonIcon.tsx
  src/components/CTextInput.tsx
  src/functions/validator.ts
  src/functions/validator/email.ts
  src/functions/validator/password.ts
  src/screens/LogIn.tsx
  src/styles/components/CButtonIcon.ts
  src/styles/components/CTextInput.ts
  src/styles/screens/Details.ts
  src/styles/screens/Following.ts
  src/styles/screens/Gps.ts
  src/styles/screens/LogIn.ts
  src/styles/screens/Settings.ts
  src/styles/screens/SignUp.ts
  src/theme/colors.ts
  src/theme/context.ts
  src/theme/themes.ts
  src/types/components/CButton.ts
  src/types/components/CButtonIcon.ts
  src/types/components/CTextInput.ts
  src/types/screens/LogIn.ts
  src/types/theme/context.ts
Labels: @IvanGodinez21

#18 Feat/#17 Sign Up screen distribution using reusable components
  src/screens/LogIn.tsx
  src/screens/SignUp.tsx
  src/styles/screens/LogIn.ts
  src/styles/screens/SignUp.ts
  src/theme/themes.ts
  src/types/screens/LogIn.ts
  src/types/screens/SignUp.ts
  src/types/theme/context.ts
Labels: @McFly1208

#20 Feat/#19 weather widget
  .vscode/settings.json
  docs/planning.md
  src/components/CWWidget.tsx
  src/screens/Gps.tsx
  src/styles/components/CWWidget.ts
  src/styles/screens/Gps.ts
  src/types/components/CWWidget.ts
Labels: @McFly1208

#22 Feat/#21 weather info
  src/clients/OWMA.ts
  src/components/CWInfo.tsx
  src/components/CWWidget.tsx
  src/screens/Gps.tsx
  src/styles/components/CWInfo.ts
  src/styles/screens/Gps.ts
  src/theme/themes.ts
  src/types/components/CWInfo.ts
  src/types/components/CWWidget.ts
  src/types/screens/Gps.ts
  src/types/theme/context.ts
Labels: @arthurchina92

#25 Feat/#23 Widget details
  .github/workflows/expo-build.yml
  .github/workflows/expo-preview.yml
  .gitignore
  app.config.ts
  babel.config.js
  package-lock.json
  package.json
  src/clients/OWMA.ts
  src/components/CWDetails.tsx
  src/firebase/config.ts
  src/screens/Gps.tsx
  src/styles/components/CWDetails.ts
  src/styles/components/CWInfo.ts
  src/styles/screens/Gps.ts
  src/types/components/CWDetails.ts
  src/types/screens/Gps.ts
Labels: @arthurchina92

#26 Feat/#24 Widget Card
  src/components/CWCard.tsx
  src/screens/Following.tsx
  src/styles/components/CWCard.ts
  src/styles/components/CWDetails.ts
  src/styles/screens/Following.ts
  src/types/components/CWCard.ts
Labels: @arthurchina92

#31 Feat/#30 Following Button
  src/screens/Details.tsx
  src/styles/screens/Details.ts
  src/theme/colors.ts
  src/theme/themes.ts
  src/types/screens/Details.ts
  src/types/theme/context.ts
Labels: @EliasCode79

#29 Feat/#28 Settings screen
  src/assets/usericon.png
  src/screens/Settings.tsx
  src/styles/screens/Settings.ts
Labels: @EliasCode79

#33 Feat/#32 Import components to details screen
  src/screens/Details.tsx
  src/types/screens/Details.ts
Labels: @EliasCode79

#35 feat/#28 Search bar functionality
  src/navigation/InFollowing.tsx
  src/navigation/InGps.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
Labels: @EliasCode79

#39 Feat/#38 Dark theme improved
  src/theme/colors.ts
Labels: @EliasCode79

#41 Feat/#39 Add background and fixed styles in CWWidget
  src/components/CWWidget.tsx
  src/styles/components/CWDetails.ts
  src/styles/components/CWInfo.ts
  src/styles/components/CWWidget.ts
  src/styles/screens/Details.ts
  src/styles/screens/Gps.ts
  src/types/components/CWWidget.ts
Labels: @EliasCode79

#47 Test/#44 Tests for `CButton`
  tests/components/CButton.test.tsx
Labels: @Matarratas777

#50 Feat/#43 CWCard redistribution
  src/components/CWCard.tsx
  src/components/CWWidget.tsx
  src/styles/components/CWCard.ts
  src/styles/components/CWWidget.ts
  src/types/components/CWWidget.ts
Labels: @Matarratas777

#53 Test/#46 Tests for `CButtonIcon`
  .github/workflows/coverage.yml
  tests/components/CButtonIcon.test.tsx
Labels: @Matarratas777

#56 Tests/#48 Test for `CWCard`
  src/components/CWCard.tsx
  src/types/components/CWCard.ts
  tests/components/CWCard.test.tsx
Labels: @Matarratas777

#55 Tests/#45 Test for `CTextInput`
  tests/components/CTextInput.test.tsx
Labels: @Matarratas777
