Repository BrightCoders-Institute/BCDIC22-RN-proyecto-final-team3, pull requests merged in 2023-04, with the labels that each got.

#58 Feat/#54 Sign up and Log in with Firebase
  src/navigation/Index.tsx
  src/screens/Account.tsx
  src/screens/LogIn.tsx
  src/screens/SignUp.tsx
  src/styles/screens/Account.ts
Labels: @Matarratas777

#61 Docs/#57 Modification of the readme file
  README.md
  img/screenshots/dark/following.png
  img/screenshots/dark/gps.png
  img/screenshots/dark/settings.png
  img/screenshots/light/following.png
  img/screenshots/light/gps.png
  img/screenshots/light/settings.png
Labels: @Matarratas777

#60 Test/#51 Tests for `CWInfo`
  .github/workflows/coverage.yml
  .github/workflows/expo-build.yml
  .github/workflows/expo-preview.yml
  jest.config.ts
  src/clients/OWMA.ts
  src/components/CWInfo.tsx
  src/types/components/CWInfo.ts
  tests/components/CWInfo.test.tsx
Labels: @Matarratas777

#64 Feat/#63 Follow and unfollow locations
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/types/screens/Following.ts
Labels: @IvanGodinez21

#59 Test/#52 Test for `CWWidget`
  src/components/CWWidget.tsx
  src/screens/Details.tsx
  src/screens/Gps.tsx
  src/types/components/CWWidget.ts
  tests/components/CWWidget.test.tsx
Labels: @IvanGodinez21

#68 Refactor/#67 Removing decimals from temperature
  README.md
  src/components/CWCard.tsx
  src/components/CWDetails.tsx
  src/components/CWWidget.tsx
Labels: @IvanGodinez21

#66 Feat/#65 Restore user last selected theme on log in
  App.tsx
  src/screens/Settings.tsx
Labels: @IvanGodinez21

#70 Refactor/#69 New weather icons
  jest.config.ts
  src/assets/owma/01d.png
  src/assets/owma/01n.png
  src/assets/owma/02d.png
  src/assets/owma/02n.png
  src/assets/owma/03d.png
  src/assets/owma/03n.png
  src/assets/owma/04d.png
  src/assets/owma/04n.png
  src/assets/owma/09d.png
  src/assets/owma/09n.png
  src/assets/owma/10d.png
  src/assets/owma/10n.png
  src/assets/owma/11d.png
  src/assets/owma/11n.png
  src/assets/owma/13d.png
  src/assets/owma/13n.png
  src/assets/owma/50d.png
  src/assets/owma/50n.png
  src/components/CWCard.tsx
  src/components/CWDetails.tsx
  src/components/CWWidget.tsx
  src/constants/icons.ts
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
  src/screens/Search.tsx
  src/styles/components/CWCard.ts
  src/styles/components/CWDetails.ts
  src/styles/components/CWWidget.ts
  src/types/components/CWDetails.ts
  tests/components/CWWidget.test.tsx
Labels: @McFly1208

#73 Refactor/#71 Loading elements
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
  src/screens/Search.tsx
  src/styles/screens/Details.ts
  src/styles/screens/Following.ts
  src/styles/screens/Gps.ts
  src/styles/screens/Search.ts
  src/theme/themes.ts
  src/types/screens/Search.ts
  src/types/theme/context.ts
Labels: @McFly1208

#74 Feat/#72 Weather wind
  .github/workflows/coverage.yml
  App.tsx
  package-lock.json
  package.json
  src/components/CWWind.tsx
  src/screens/Details.tsx
  src/screens/Following.tsx
  src/screens/Gps.tsx
  src/styles/components/CWInfo.ts
  src/styles/components/CWWind.ts
  src/styles/screens/Details.ts
  src/styles/screens/Gps.ts
  src/types/components/CWWind.ts
  src/types/screens/Following.ts
  tests/components/CWWind.test.tsx
Labels: @arthurchina92
